[build]
functions = "netlify/functions"
publish = "."

[[redirects]]
	from = "/insights"
	to = "/insights/index.html"
	status = 200

[[redirects]]
	from = "/insights/"
	to = "/insights/index.html"
	status = 200

[[redirects]]
	from = "/insights/*"
	to = "/insights/article.html"
	status = 200
